### PR TITLE
Fix to support compiling under VS2015 VC140

### PR DESCRIPTION
**Pull request by stunney**
Apparently MACROs now require whitespace around them.

### CODE REVIEW

**Comment by stunney** [comment]
@mnunberg I am unable to connect to review.couchbase.org:29418 due to corporate firewall rules.  Can we forgo the gerrit setup?  I go all the way to
Initial Project Setup (for each project)
before everything started to go sideways.

**Comment by mnunberg** [comment]
I can't see if you signed the CLA. If you signed the CLA, can you tell me which email or id you're using so we can correlate?

If you signed the CLA, I can upload the changes to gerrit for you.

**Comment by stunney** [comment]
I used s_tunney2000@yahoo.com
Thank you very much!

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 21, 2016 at 2:48 PM, M. Nunberg<notifications@github.com> wrote:   
I can't see if you signed the CLA. If you signed the CLA, can you tell me which email or id you're using so we can correlate?

If you signed the CLA, I can upload the changes to gerrit for you.

**Comment by stunney** [comment]
There appears to be another issue with the VS 2015 builds.  The file https://github.com/couchbase/libcouchbase/blob/master/include/libcouchbase/configuration.h.in does not get converted into "configuration.h" in the same folder.  This is causing a compiler error for clients because couchbase.h is including "libcouchbase/configuration.h

Am I missing a build step before/after the two cmake calls?

**Comment by stunney** [comment]
Oh, NVM.  Found it under /build/generated/libcouchbase.

Do I need the config.h that is generated as well?  Looks superfluous.

**Comment by mnunberg** [comment]
That might be because I'm not properly declaring what the "INCLUDE" directories for the libraries are in CMake. You need to run the install target in order to end up with a distributable that's actually usable by other components.

The `config.h` is only needed for internal usage.

**Comment by stunney** [comment]
so that command would be cmake --install .\
?

**Comment by stunney** [comment]
Oh, and in case you didn't see.  I've written a nuget packaging definition for use with the CoApp powershell tools.  For our purposes, nuget will be 100% required since we have oh, about 300 C++ projects that will be using couchbase in the near future :)

**Comment by mnunberg** [comment]
Here is what I use to build the packages for release.. some lines might not be relevant to you (like the tests):

```bat
echo PATH=%PATH%
echo MSVCC_VER=%MSVCC_VER%
echo ARCH=%ARCH%

IF %MSVCC_VER% EQU 9 SET cmgen=Visual Studio 9 2008
IF %MSVCC_VER% EQU 10 SET cmgen=Visual Studio 10 2010
IF %MSVCC_VER% EQU 11 SET cmgen=Visual Studio 11 2012
IF %ARCH% EQU amd64 SET cmgen=%cmgen% Win64

RD /s /q BUILD
MKDIR BUILD
CD BUILD

cmake -G"%cmgen%" -DLCB_NO_SSL=1 ..\libcouchbase

cmake --build .
cmake --build . --target package
cmake --build . --target alltests
ctest -C debug
```

**Comment by stunney** [comment]
I have agreed to the CLA under my github account.

**Comment by brett19** [comment]
Hey @stunney ,
If you look at the commits that are part of this Pull Request, there are two author emails, one I believe you have registered on Gerrit with, and the other is not associated.
Cheers, Brett

**Comment by stunney** [comment]
All of the commits should be under my github account (I have only one).  I originally signed the Garret under my yahoo account but I just (an hour ago) signed with my github oauth2 connection.

**Comment by stunney** [comment]
Sorry, gerrit :)

**Comment by brett19** [comment]
Hey @stunney,
Though your GitHub account has only a single email, your commits themselves are committed under an by a specific identify.  This is the email which is not matching.
Cheers, Brett

**Comment by stunney** [comment]
The stephen.tunney@ account?  Ok.  I will see if I can link this up.

**Comment by brett19** [comment]
Hey @stunney,
Would you be able to grab me your Gerrit account number (it's available in Settings).  I don't see either of your commit emails in Gerrit, it's possible there is a bug in the verification process.
Cheers, Brett

**Comment by stunney** [comment]
1003775
Gerrit won't let me get to settings in Chrome on my phone.  Bug!! ;)

**Comment by brett19** [comment]
Hey @stunney,
I took a look at that account, it doesn't appear to have any email addresses associated with it :)  From your settings, please add both your emails, and then this commit should go through without issue.
Cheers, Brett

**Comment by stunney** [comment]
It has been done.

**Comment by mnunberg** [comment]
This has been merged by gerrit. Thank you for your contribution!

**Pull request closed without merging**
