### PR TITLE
New cberl link

### PR DESCRIPTION
**Pull request by wcummings**
Update cberl link, Chitika org defunct, future development will happen in my repo

### CODE REVIEW

**Comment by mnunberg** [comment]
Can you follow the Robot's advice?

**Comment by wcummings** [comment]
I thought I did.

**Comment by mnunberg** [comment]
Should show up here (http://review.couchbase.org/#/q/project:libcouchbase+status:open) if you followed everything accordingly. Ensure your gerrit and github email match (also the one you used in the commit).

**Comment by wcummings** [comment]
Ah I bet the commit email doesn't match, I'll sort it

**Comment by wcummings** [comment]
Looks like the right email:

localemail
screenshot from 2017-02-01 14-04-45
3653/22521866/6f605db6-e887-11e6-8d7e-8c77dcc2e194.png)

Anything else I should check?

**Comment by wcummings** [comment]
Got it :) @mnunberg

**Comment by brett19** [comment]
Sorry, there was probably a bit of confusion as the bot was behaving a bit strange after an update to our Gerrit instance last night.  Should be good now :)

**Comment by wcummings** [comment]
I think it was just that the email on the commit didn't match, once I pushed w/ the correct email it was happy

**Pull request closed without merging**
