### PR TITLE
Add bucket to the connection config cache

### PR DESCRIPTION
**Pull request by JordyMoos**
Which will store a typology file per bucket. Prevent crashing if want to open multiple buckets.

Now if you provide a `config_cache` to the connection. Then that path is used for all buckets. Opening a second bucket will then crash because the cache data does not belong to the bucket.
Adding the bucket name as suffix will create unique paths per bucket.

This suffix was already applied when not supplying a directory. Now its applied on both scenarios.

Todo:
- [ ] Discuss this problem/fix
- [ ] After that: fix tests

### CODE REVIEW

**Comment by JordyMoos** [comment]
I already signed one a few years ago @cb-sdk-robot , Do I need to do it again?

I made some PR's here:
https://github.com/brett19/php-couchbase/pulls?q=is%3Apr+is%3Aclosed+author%3AJordyMoos

**Comment by avsej** [comment]
@JordyMoos, did you use the same email as you are using here? Gerrit sees something matching this wildcard: `j***y@pbwe******.com`

**Comment by JordyMoos** [comment]
@avsej Yes I did use the same email

**Comment by avsej** [comment]
Could you upload directly to gerrit? 

1) Just add your SSH key http://review.couchbase.org/settings#SSHKeys (just like on github) and make sure you have set your username there. 

2) Add gerrit as a second git remote

    git remote add gerrit ssh://{YOUR_GERRIT_NAME}@review.couchbase.org:29418/libcouchbase

3) Assuming your local `HEAD` is the branch pointing  to`JordyMoos:config_cache-file-per-bucket`

    git push gerit HEAD:refs/heads/master

After that the gerrit will render a link in your terminal, and I will see it in my review list

**Comment by JordyMoos** [comment]
> fatal: Upload denied for project 'libcouchbase'
> fatal: Could not read from remote repository.

Denied

**Comment by avsej** [comment]
What does it say when you execute `git fetch gerrit`? Also I noticed that your branch was derived from `release-2.10`, so the submit command would be

     git push gerit HEAD:refs/heads/release-2.10

**Comment by avsej** [comment]
Another diagnostic command might be trying to connect to gerrit using SSH (assuming you are using the same SSH key). It checks access and should report if there are any problems

```
$ ssh -p 29418 review.couchbase.org

  ****    Welcome to Gerrit Code Review    ****

  Hi Sergey Avseyev, you have successfully connected over SSH.

  Unfortunately, interactive shells are disabled.
  To clone a hosted Git repository, use:

  git clone ssh://avsej@review.couchbase.org:29418/REPOSITORY_NAME.git

Connection to review.couchbase.org closed.
```

**Comment by avsej** [comment]
@JordyMoos, I've just checked those old commits, and it seems like at the time the PHP SDK didn't use gerrit, so there wasn't CLA check at all. Could you please make use you have signed CLA here http://review.couchbase.org/#/settings/new-agreement. It should show something like this

**Comment by JordyMoos** [comment]
I just signed the agreement digitally. I suppose that is enough?


I branched from 2.10.4 because I was not sure about the release-2.10 branch. I did not branch from master because I'm using version 2 and I was hoping that the fix could be released in version 2.

I could not push to gerrit release-2.10 because I was behind. I merged release-2.10 into my branch. And now I can not push to gerrit because of permission denied:
```To ssh://review.couchbase.org:29418/libcouchbase
 ! [remote rejected]   HEAD -> release-2.10 (prohibited by Gerrit: ref update access denied)```

Would you like me to redo the changes but then branched from release-2.10?

**Comment by avsej** [comment]
@JordyMoos, sorry I gave wrong command

 git push gerit HEAD:refs/**for**/release-2.10

It should be `refs/for/release-2.10` instead of `refs/heads/release-2.10`

**Comment by avsej** [comment]
@JordyMoos thanks for submitting it. I've moved your patch to correct branch at http://review.couchbase.org/c/112649/

**Comment by JordyMoos** [comment]
Thanks @avsej

**Comment by avsej** [comment]
@JordyMoos I've updated the fix a bit, because with your implementation it is not possible to get old behaviour, when you want to pass particular file name as a cache. I changed it to look for last character, and if it is `/` then treat argument as a directory and append bucket name. If you have any questions, we can continue it in the gerrit comments

**Pull request closed without merging**
