### PR TITLE
Add PHP to list of client libraries

### PR DESCRIPTION
**Pull request by kojiromike**

### CODE REVIEW

**Comment by kojiromike** [comment]
bump?

**Comment by mnunberg** [comment]
To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA.  More detailed instructions are available here: https://developer.couchbase.com/open-source-projects#how-to-contribute-code.

**Comment by kojiromike** [comment]
I don't want to do that for a one-line change to a README file. I respect your desire for process, but for a change this small I believe you should be able to accept it without ceremony.

**Comment by mnunberg** [comment]
We cannot accept pull requests for two reasons:

1. Commits bypassing our code review system will confuse it. So even if this commit in itself is trivial, our code review system is required for commits which are not; because Gerrit requires that it be the only entity pushing to the master repository, it means even trivial commits must bypass code review, even if the review is nothing more than nominal
2. Our legal department had mandated that anyone making contributions to Couchbase projects need to sign a CLA (Contributor License Agreement) essentially acknowledging that the contributions made fall under the license and copyright of the project in general.

We are working on making these steps easier by attempting to integrate our code review system with GitHub's pull requests APIs.

I can fix the typo myself, though it would technically be a different commit.

**Comment by mnunberg** [comment]
See http://review.couchbase.org/#/c/62955/ for something similar.

**Comment by kojiromike** [comment]
@mnunberg All good. Thanks for taking the time.

**Pull request closed without merging**
